/**
 * RIC subscription
 * This is the initial REST API for RIC subscription
 *
 * OpenAPI spec version: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.27-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * RegisterData.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_RegisterData_H_
#define IO_SWAGGER_CLIENT_MODEL_RegisterData_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  RegisterData
    : public ModelBase
{
public:
    RegisterData();
    virtual ~RegisterData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// RegisterData members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAppName() const;
    bool appNameIsSet() const;
    void unsetAppName();
    RegisterData& setAppName(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getHttpEndpoint() const;
    bool httpEndpointIsSet() const;
    void unsetHttpEndpoint();
    RegisterData& setHttpEndpoint(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getRmrEndpoint() const;
    bool rmrEndpointIsSet() const;
    void unsetRmrEndpoint();
    RegisterData& setRmrEndpoint(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAppInstanceName() const;
    bool appInstanceNameIsSet() const;
    void unsetAppInstanceName();
    RegisterData& setAppInstanceName(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAppVersion() const;
    bool appVersionIsSet() const;
    void unsetAppVersion();
    RegisterData& setAppVersion(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getConfigPath() const;
    bool configPathIsSet() const;
    void unsetConfigPath();
    RegisterData& setConfigPath(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getConfig() const;
    bool configIsSet() const;
    void unsetConfig();
    RegisterData& setConfig(utility::string_t value);

protected:
    utility::string_t m_AppName;
    bool m_AppNameIsSet;
    utility::string_t m_HttpEndpoint;
    bool m_HttpEndpointIsSet;
    utility::string_t m_RmrEndpoint;
    bool m_RmrEndpointIsSet;
    utility::string_t m_AppInstanceName;
    bool m_AppInstanceNameIsSet;
    utility::string_t m_AppVersion;
    bool m_AppVersionIsSet;
    utility::string_t m_ConfigPath;
    bool m_ConfigPathIsSet;
    utility::string_t m_Config;
    bool m_ConfigIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_RegisterData_H_ */
